spring.application.name=cvbot
server.port=${PORT:8090}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}

puppeteer.script.path=${PUPPETEER_SCRIPT_PATH:/app/convert.js}


stripe.success.url=https://t.me/cv_az_bot
stripe.cancel.url=https://t.me/cv_az_bot

