spring.application.name=cvbot
server.port=${PORT:8090}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/cvbot}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

puppeteer.script.path=${PUPPETEER_SCRIPT_PATH:C:\\cvbot-pdf\\convert.js}

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.success.url=https://t.me/cv_az_bot
stripe.cancel.url=https://t.me/cv_az_bot

cv.price=5.00