[phases.setup]
nixPkgs = ["nodejs_20", "maven", "jdk17", "chromium", "nss", "alsa-lib", "at-spi2-core", "libdrm", "mesa", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXrandr"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
    "chmod +x mvnw",
    "./mvnw clean package -DskipTests"
]

[start]
cmd = "java -jar target/cvbot-0.0.1-SNAPSHOT.jar"